version: "3.1"
services:
  mariadb-service:
    container_name: db-server
    image: mariadb:latest
    ports:
      - "3306:3306"
    network_mode: host
    environment: { "MARIADB_ROOT_PASSWORD": "123" }
  wt-service:
    container_name: main-server
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    network_mode: host
