version: "0.1"
services:
  mariadb-service:
    container_name: db-server
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment: { "MARIADB_ROOT_PASSWORD": "123" }
    networks:
      - host
  wt:
    container_name: main-server
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - host

network:
  host:
    name: host
    external: true
