services:
  mariadb-service:
    container_name: db-server
    image: mariadb:latest
    ports:
      - "3306:3306"
    networks:
      - my_network
    environment: { "MARIADB_ROOT_PASSWORD": "123" }
  wt-service:
    container_name: main-server
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: host
