version: "0.1"
services:
  mariadb-service:
    container_name: db-server
    image: mariadb:latest
    network: host
    ports:
      - "3306:3306"
    environment: { "MARIADB_ROOT_PASSWORD": "123" }
    
  wt:
    container_name: main-server
    build: .
    network: host
    ports:
      - "8080:8080"
      - "8081:8081"
network:
  host:
    name: host
    external: true
